<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__groupId</name>
   <tag></tag>
   <elementGuidId>1d7cc9e1-328b-4b7d-b390-f60e266a6bad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='groupId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#groupId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1653519e-7f76-4deb-8af7-f24aa35652dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>groupId</value>
      <webElementGuid>0e7b4edd-fa80-4c11-a93b-5c87df719d39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-border aria-invalid:border-destructive aria-invalid:placeholder:text-destructive file:text-foreground disabled:bg-disabled/60 flex h-10 w-full rounded-md border bg-transparent px-2 text-xs font-normal transition-colors file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-xs placeholder:text-neutral-50 focus-visible:border-neutral-50 focus-visible:bg-transparent focus-visible:outline-none disabled:cursor-not-allowed disabled:text-neutral-100 md:h-12 md:px-4 md:text-sm md:placeholder:text-sm</value>
      <webElementGuid>f6864f04-fb5a-4840-92d1-324ad9d90f8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input Item Group Id</value>
      <webElementGuid>c61a9e0a-6d97-40d5-8929-01818e0c6ba6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;groupId&quot;)</value>
      <webElementGuid>73fc2a0d-1184-45e1-a4f1-274bc0f41de9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='groupId']</value>
      <webElementGuid>77ee9628-7dd0-478c-b5c8-866edabea3c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-_r_1o_']/div[2]/div/div/div/input</value>
      <webElementGuid>7d225347-2287-431e-b5ac-2e4c3cb94cd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>faf42c9e-c0e6-41bf-8670-4b4474fe870a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'groupId' and @placeholder = 'Input Item Group Id']</value>
      <webElementGuid>3ba442ca-05e7-47c1-a6dd-7f7a44e57847</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
