<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__groupName</name>
   <tag></tag>
   <elementGuidId>054b6e07-94d1-41d4-ab0c-f1908b37e3ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='groupName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#groupName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>059f62a3-4455-4ca1-949a-f33777d1e57f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>groupName</value>
      <webElementGuid>627d79c0-8f9c-402a-b139-68c6f3c9c89a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-border aria-invalid:border-destructive aria-invalid:placeholder:text-destructive file:text-foreground disabled:bg-disabled/60 flex h-10 w-full rounded-md border bg-transparent px-2 text-xs font-normal transition-colors file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-xs placeholder:text-neutral-50 focus-visible:border-neutral-50 focus-visible:bg-transparent focus-visible:outline-none disabled:cursor-not-allowed disabled:text-neutral-100 md:h-12 md:px-4 md:text-sm md:placeholder:text-sm</value>
      <webElementGuid>8a672529-8878-4ef1-9895-02b4744d1747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input Item Group Name</value>
      <webElementGuid>ed1d5d34-5f1d-4414-bae3-697d2fa18389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;groupName&quot;)</value>
      <webElementGuid>4227c3b1-c590-4612-91a1-abd91e39bf8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='groupName']</value>
      <webElementGuid>087b833d-c807-46be-81a6-02c693f8291d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-_r_1m_']/div[2]/div[2]/div/div/input</value>
      <webElementGuid>3c9070b4-5231-4ba7-a630-ddb5e6bdb5db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>d9e2a856-5ea5-46d6-b68a-002cb8b7626e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'groupName' and @placeholder = 'Input Item Group Name']</value>
      <webElementGuid>d5f91238-6f52-4581-95ba-0c28caa903b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
