<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PopUp_Edit Detail</name>
   <tag></tag>
   <elementGuidId>5b5344ad-2238-4472-97d0-93fd461a9186</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h2[contains(text(), 'Edit Item Group')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#radix-_r_1t_</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>027cf214-a786-42b0-9c68-a1ca6bd483c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>7cfdf179-f58f-4182-ab8e-d1f83852db23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radix-_r_1t_</value>
      <webElementGuid>a01fbb49-159e-4429-b4fd-c4673640e419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>radix-_r_1v_</value>
      <webElementGuid>4108f6ac-542b-4034-ba59-23e25887d470</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>radix-_r_1u_</value>
      <webElementGuid>1599bb93-8f95-4c25-a064-8f147ed46175</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>open</value>
      <webElementGuid>cee61241-491c-494c-9fd2-38c6668b27a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-background data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 data-[state=closed]:slide-out-to-left-1/2 data-[state=closed]:slide-out-to-top-[48%] data-[state=open]:slide-in-from-left-1/2 data-[state=open]:slide-in-from-top-[48%] fixed top-[50%] left-[50%] z-50 grid w-full max-w-lg translate-x-[-50%] translate-y-[-50%] gap-4 p-6 shadow-lg duration-200 sm:rounded-lg sm:max-w-lg [&amp;>button]:h-10 [&amp;>button]:w-10 [&amp;>button]:text-gray-400 [&amp;>button]:hover:text-gray-600 [&amp;>button>svg]:h-6 [&amp;>button>svg]:w-6</value>
      <webElementGuid>4709a4ac-8669-4710-8ed5-4a4b8986877b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>b41f625a-f843-455f-b802-1b28bf668232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Item GroupItem Group Id *Item Group Name *ActiveClose</value>
      <webElementGuid>16c59fc5-f1d9-4ad2-8e4b-eb99781b75e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-_r_1t_&quot;)</value>
      <webElementGuid>242bb036-a626-4ea9-b5d2-a6637d3a1e5d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='radix-_r_1t_']</value>
      <webElementGuid>c6008ec1-16db-4db4-b0da-132b32cad496</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2025 Sinar Mas Land. All Rights Reserved. Corporate Information Technology.'])[1]/following::div[2]</value>
      <webElementGuid>e4bc6d7e-d26d-4151-8a0a-d496940cb03e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]</value>
      <webElementGuid>0bfe4782-4d89-45f1-aca8-e4695597f340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'radix-_r_1t_' and (text() = 'View Item GroupItem Group Id *Item Group Name *ActiveClose' or . = 'View Item GroupItem Group Id *Item Group Name *ActiveClose')]</value>
      <webElementGuid>b7a8ccd5-72c9-41b3-bfa3-3ec9dd730d9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
