<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PopUp_View Detail</name>
   <tag></tag>
   <elementGuidId>104b08f9-6bfc-44aa-a8dd-d9173d0bb19f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#radix-_r_1t_</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[contains(text(), 'View Item Group')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>70ff8b5e-f42e-4efc-af96-8a6b4497cac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>d91480ce-c0ba-42e6-9485-0899c7ae2891</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radix-_r_1t_</value>
      <webElementGuid>a5828c43-b822-47d7-8048-a87d73b36c9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>radix-_r_1v_</value>
      <webElementGuid>e5a7d40a-3f03-4a07-945a-89fcf065c2eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>radix-_r_1u_</value>
      <webElementGuid>99f4337e-bc2c-4aa1-a2bf-467822314109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>open</value>
      <webElementGuid>a6b0971b-3058-497f-9092-3def98e8bfe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-background data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 data-[state=closed]:slide-out-to-left-1/2 data-[state=closed]:slide-out-to-top-[48%] data-[state=open]:slide-in-from-left-1/2 data-[state=open]:slide-in-from-top-[48%] fixed top-[50%] left-[50%] z-50 grid w-full max-w-lg translate-x-[-50%] translate-y-[-50%] gap-4 p-6 shadow-lg duration-200 sm:rounded-lg sm:max-w-lg [&amp;>button]:h-10 [&amp;>button]:w-10 [&amp;>button]:text-gray-400 [&amp;>button]:hover:text-gray-600 [&amp;>button>svg]:h-6 [&amp;>button>svg]:w-6</value>
      <webElementGuid>ecf96371-ff62-49d6-a81a-632a80117adf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>a5bf7d3a-45fa-465f-a962-e69743e8723a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Item GroupItem Group Id *Item Group Name *ActiveClose</value>
      <webElementGuid>1152b797-6778-4243-b83e-19536cf793de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-_r_1t_&quot;)</value>
      <webElementGuid>193fcb7b-dfab-41ea-9a2d-d30a89053b79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='radix-_r_1t_']</value>
      <webElementGuid>690ba8f6-3d6a-442f-bd96-7642e56cd4e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2025 Sinar Mas Land. All Rights Reserved. Corporate Information Technology.'])[1]/following::div[2]</value>
      <webElementGuid>0b8638fa-903b-4267-8d7d-0838f2bd03fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]</value>
      <webElementGuid>7ee34aa1-14c0-4672-9410-38b7fd59ab1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'radix-_r_1t_' and (text() = 'View Item GroupItem Group Id *Item Group Name *ActiveClose' or . = 'View Item GroupItem Group Id *Item Group Name *ActiveClose')]</value>
      <webElementGuid>34bc818f-45cc-463c-8055-f4df822cc92d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
