<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>toggle_Status</name>
   <tag></tag>
   <elementGuidId>65928988-f369-4dd3-8edd-605133c5bb1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@role='switch']&#xd;
</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>11f6ce98-36bc-4679-b8e3-cbdace50f8d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>absolute inset-0 flex items-center justify-center font-medium text-white transition-opacity duration-200 text-[10px] opacity-0</value>
      <webElementGuid>9db296ec-d6b2-47d3-a0c0-14d0221bd21b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;active&quot;)/span[@class=&quot;absolute inset-0 flex items-center justify-center font-medium text-white transition-opacity duration-200 text-[10px] opacity-0&quot;]</value>
      <webElementGuid>ddcdeec4-dd0c-469f-8dc2-bddec2bc358d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='active']/span[2]</value>
      <webElementGuid>261385d7-6e8b-4d89-9c1d-475737d8c979</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span[2]</value>
      <webElementGuid>d19efad0-0f7b-43d9-82ef-63b702ba9a86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
