<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__description</name>
   <tag></tag>
   <elementGuidId>52377b7b-2315-40d2-9867-a80ba5acad31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='description']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#description</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f205774f-bc6d-4208-b0a9-3c292f2c9079</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>description</value>
      <webElementGuid>fdb34971-a872-452b-a378-75f421a3472f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-border aria-invalid:border-destructive aria-invalid:placeholder:text-destructive file:text-foreground disabled:bg-disabled/60 flex h-10 w-full rounded-md border bg-transparent px-2 text-xs font-normal transition-colors file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-xs placeholder:text-neutral-50 focus-visible:border-neutral-50 focus-visible:bg-transparent focus-visible:outline-none disabled:cursor-not-allowed disabled:text-neutral-100 md:h-12 md:px-4 md:text-sm md:placeholder:text-sm</value>
      <webElementGuid>02ab43cb-3d30-4b5a-994e-379e1aef69ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Input Item Subcategory Name</value>
      <webElementGuid>42db8bcf-a73f-4ba5-a96a-8ede8b412d70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;description&quot;)</value>
      <webElementGuid>4336e685-2706-40f0-b255-0d2aa12d888d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='description']</value>
      <webElementGuid>b7ef66e3-f1d6-4b6b-9d26-7e2d6d9b1508</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='radix-_r_1n_']/div[2]/div/div/div/input</value>
      <webElementGuid>59e04f8c-eae5-4f74-92bd-863e85f5f1e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/input</value>
      <webElementGuid>ecfd1376-18cb-46c3-9ead-08b78dc47de6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'description' and @placeholder = 'Input Item Subcategory Name']</value>
      <webElementGuid>31344a69-30cf-40be-ae0f-80b7e38fc59e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
