<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PopUp_View Detail</name>
   <tag></tag>
   <elementGuidId>31c6c268-4736-49fe-a8b3-f1497cfcaea5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h2[contains(text(), 'View Item Subcategory')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#radix-_r_1t_</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c7eabb2b-60d1-4250-8b2e-ee4d85f35cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>ef369a01-c838-4043-89bc-43e2d2116de4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radix-_r_1t_</value>
      <webElementGuid>935790d2-c5a6-41e5-87d6-4e319365262f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>radix-_r_1v_</value>
      <webElementGuid>6a4fd452-7f54-4f5e-aa7a-9598392d243a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>radix-_r_1u_</value>
      <webElementGuid>aebcf39e-8119-42a3-858c-93e2a6bc9568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>open</value>
      <webElementGuid>94dd7d28-6c26-43f4-85cc-9d4d8469e49f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bg-background data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 data-[state=closed]:slide-out-to-left-1/2 data-[state=closed]:slide-out-to-top-[48%] data-[state=open]:slide-in-from-left-1/2 data-[state=open]:slide-in-from-top-[48%] fixed top-[50%] left-[50%] z-50 grid w-full max-w-lg translate-x-[-50%] translate-y-[-50%] gap-4 p-6 shadow-lg duration-200 sm:rounded-lg sm:max-w-lg [&amp;>button]:h-10 [&amp;>button]:w-10 [&amp;>button]:text-gray-400 [&amp;>button]:hover:text-gray-600 [&amp;>button>svg]:h-6 [&amp;>button>svg]:w-6</value>
      <webElementGuid>f89ed6df-1e68-48c9-a547-a38b67665c00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>34170030-74c3-40c4-9ae2-92732bc68eac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>View Item GroupItem Group Id *Item Group Name *ActiveClose</value>
      <webElementGuid>88e9062d-e4a5-498c-8899-e16b3aca0a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radix-_r_1t_&quot;)</value>
      <webElementGuid>c6a1b5c7-1e87-419d-947f-88565e9d4db2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='radix-_r_1t_']</value>
      <webElementGuid>444bcd06-3265-40cd-8fb4-c703b44b6687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='© 2025 Sinar Mas Land. All Rights Reserved. Corporate Information Technology.'])[1]/following::div[2]</value>
      <webElementGuid>ed95138d-089f-4ffc-988f-5b17315ba1b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]</value>
      <webElementGuid>7da9a960-442e-4dbc-9e86-133a8c0e9385</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'radix-_r_1t_' and (text() = 'View Item GroupItem Group Id *Item Group Name *ActiveClose' or . = 'View Item GroupItem Group Id *Item Group Name *ActiveClose')]</value>
      <webElementGuid>537f5b31-5bc4-44c3-afc2-6877b3b60f44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
