<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Apply to All_1</name>
   <tag></tag>
   <elementGuidId>f6b0d62b-91d7-463d-ac57-452eba56c473</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[15]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>efa43ddc-2a4e-434b-b309-bb5a0f0a8f59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex items-center disabled:cursor-not-allowed cursor-pointer whitespace-nowrap rounded-lg md:text-sm transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none [&amp;_svg]:pointer-events-none [&amp;_svg]:size-4 [&amp;_svg]:shrink-0 border border-secondary bg-background hover:bg-accent hover:text-accent-foreground py-2 md:px-6 md:py-3 flex-1 h-9 justify-between px-3 text-sm text-left font-normal min-w-0 text-muted-foreground</value>
      <webElementGuid>26e8882c-65e0-4b89-be89-efa78b456365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>7f87c536-b863-40b3-b2ad-dd2979b1682c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e37917eb-7ef0-46c5-8b21-c6e80d374955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>03572b77-68df-41d6-918e-2d6d8cc9de27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>70aeb74e-ddd9-4703-bd93-01e1baa2e0d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>radix-_r_55_</value>
      <webElementGuid>e148fd02-16ab-4f5b-aa64-e758c29d2e59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>closed</value>
      <webElementGuid>2225b28b-6619-4744-9ca4-1098878b47eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apply to All</value>
      <webElementGuid>d0bfb2b1-dd8e-4951-83f1-23d2e4fc847e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;inter_5972bc34-module__OU16Qa__className&quot;]/body[1]/div[@class=&quot;flex min-h-screen text-gray-900&quot;]/div[@class=&quot;flex min-w-0 flex-1 flex-col transition-all duration-300 ease-in-out lg:ml-[260px]&quot;]/main[@class=&quot;flex-1 overflow-x-auto bg-white p-5&quot;]/div[@class=&quot;h-[calc(100vh-64px)] w-full bg-gray-50&quot;]/div[@class=&quot;flex h-full flex-col bg-background&quot;]/div[@class=&quot;flex-1 overflow-auto p-6&quot;]/div[@class=&quot;w-full&quot;]/form[@class=&quot;space-y-8&quot;]/div[@class=&quot;overflow-hidden rounded-xl border bg-card p-6 shadow-sm min-h-[500px]&quot;]/div[2]/div[@class=&quot;space-y-8&quot;]/div[@class=&quot;overflow-x-auto pb-4&quot;]/div[@class=&quot;min-w-max&quot;]/div[@class=&quot;grid items-center gap-x-4 mb-3 p-2 rounded-md border border-transparent hover:border-gray-200 hover:bg-slate-50 transition-colors&quot;]/div[7]/div[@class=&quot;relative&quot;]/div[@class=&quot;flex items-center gap-2 w-full h-9&quot;]/button[@class=&quot;inline-flex items-center disabled:cursor-not-allowed cursor-pointer whitespace-nowrap rounded-lg md:text-sm transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none [&amp;_svg]:pointer-events-none [&amp;_svg]:size-4 [&amp;_svg]:shrink-0 border border-secondary bg-background hover:bg-accent hover:text-accent-foreground py-2 md:px-6 md:py-3 flex-1 h-9 justify-between px-3 text-sm text-left font-normal min-w-0 text-muted-foreground&quot;]</value>
      <webElementGuid>2498a86e-bca6-4206-8c67-366211258f7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[15]</value>
      <webElementGuid>b74d52d6-a627-4fdb-8e99-fe9f7ae34a39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ciello'])[1]/following::button[2]</value>
      <webElementGuid>a7ff7289-7aef-4fcb-a2a3-f63b335449d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keramik/HT 20-40 cm'])[1]/following::button[4]</value>
      <webElementGuid>5709d074-5f8c-4635-810c-97e8e40e6eb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply to All'])[2]/preceding::button[2]</value>
      <webElementGuid>8109fa11-9815-4b95-ac54-dd171adc1d07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/button</value>
      <webElementGuid>528f3f8e-74d3-4029-a20b-eb0d31fb502e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Apply to All' or . = 'Apply to All')]</value>
      <webElementGuid>3d1b3f79-3a3d-4ab4-8abe-026283a45b9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
