<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Apply to All</name>
   <tag></tag>
   <elementGuidId>f644e1f6-f389-496d-9476-1f228c714f24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//button[@type='button'])[13]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>11903271-a647-4d8f-98de-47cc046624cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>inline-flex items-center disabled:cursor-not-allowed cursor-pointer whitespace-nowrap rounded-lg md:text-sm transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none [&amp;_svg]:pointer-events-none [&amp;_svg]:size-4 [&amp;_svg]:shrink-0 border border-secondary bg-background hover:bg-accent hover:text-accent-foreground py-2 md:px-6 md:py-3 flex-1 h-9 justify-between px-3 text-sm text-left font-normal min-w-0 text-muted-foreground</value>
      <webElementGuid>3b207c1f-bb4c-48e6-af64-1c111ffd4f19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>4ac6da21-f704-4754-9e0f-4dc62857920e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>09f312de-0874-48ab-ba45-3d20dacd96d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b0bd4245-ca1e-4fce-b291-0927e2e7a7d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>dialog</value>
      <webElementGuid>c94d5326-bea3-488a-9bfa-49ce06999a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>radix-_r_52_</value>
      <webElementGuid>e267b6a4-7f57-40be-adc5-fec3c7627c6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-state</name>
      <type>Main</type>
      <value>closed</value>
      <webElementGuid>039b0567-5c3d-4da9-9b67-83d276d5f051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apply to All</value>
      <webElementGuid>01f4c3a6-df25-4ead-81ee-07b4b3685605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;inter_5972bc34-module__OU16Qa__className&quot;]/body[1]/div[@class=&quot;flex min-h-screen text-gray-900&quot;]/div[@class=&quot;flex min-w-0 flex-1 flex-col transition-all duration-300 ease-in-out lg:ml-[260px]&quot;]/main[@class=&quot;flex-1 overflow-x-auto bg-white p-5&quot;]/div[@class=&quot;h-[calc(100vh-64px)] w-full bg-gray-50&quot;]/div[@class=&quot;flex h-full flex-col bg-background&quot;]/div[@class=&quot;flex-1 overflow-auto p-6&quot;]/div[@class=&quot;w-full&quot;]/form[@class=&quot;space-y-8&quot;]/div[@class=&quot;overflow-hidden rounded-xl border bg-card p-6 shadow-sm min-h-[500px]&quot;]/div[2]/div[@class=&quot;space-y-8&quot;]/div[@class=&quot;overflow-x-auto pb-4&quot;]/div[@class=&quot;min-w-max&quot;]/div[@class=&quot;grid items-center gap-x-4 mb-3 p-2 rounded-md border border-transparent hover:border-gray-200 hover:bg-slate-50 transition-colors&quot;]/div[6]/div[@class=&quot;relative&quot;]/div[@class=&quot;flex items-center gap-2 w-full h-9&quot;]/button[@class=&quot;inline-flex items-center disabled:cursor-not-allowed cursor-pointer whitespace-nowrap rounded-lg md:text-sm transition-colors focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none [&amp;_svg]:pointer-events-none [&amp;_svg]:size-4 [&amp;_svg]:shrink-0 border border-secondary bg-background hover:bg-accent hover:text-accent-foreground py-2 md:px-6 md:py-3 flex-1 h-9 justify-between px-3 text-sm text-left font-normal min-w-0 text-muted-foreground&quot;]</value>
      <webElementGuid>d4a3b476-b3be-4bda-8e53-579b9ea32e92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[13]</value>
      <webElementGuid>0457178b-9835-4a8b-8aae-c51589186108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keramik/HT 20-40 cm'])[1]/following::button[2]</value>
      <webElementGuid>1b1bd1e3-7922-4307-8fed-d4d0315f1ab5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Keramik/HT'])[2]/following::button[3]</value>
      <webElementGuid>69d00966-29fa-4dee-8419-d5174c27add0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply to All'])[2]/preceding::button[2]</value>
      <webElementGuid>36318967-aca0-4160-b7dc-f5d433be2977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/button</value>
      <webElementGuid>c04499ee-dcf0-4d1c-a6d3-6e8d05b7aadd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Apply to All' or . = 'Apply to All')]</value>
      <webElementGuid>06d8e9ba-e52c-4b89-b9f2-77bb9247012c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
